import Navbar from '@/ui/Navigation/Navbar'
import './globals.css'
import Providers from '@/lib/providers/Providers'
import FooterPlayer from 'ui/Components/Players/FooterPlayer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='relative bg-white dark:bg-black'>
        <Providers>
        <Navbar/>
        <div className='relative top-20 pb-16 '>
        {children}
        </div>
        <FooterPlayer/>
        </Providers>
        </body>
    </html>
  )
}
