import Providers from '@/lib/providers/Providers'
import Navbar from '@/ui/Navigation/Navbar'
import FooterPlayer from 'ui/Components/Players/FooterPlayer'
import './globals.css'

export const metadata = {
  title: 'CRIB Music Global',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='relative bg-white dark:bg-black overflow-hidden'>
        <Providers>
          <Navbar />
          <div className='relative min-h-full h-full overflow-y-auto'>
            {children}
          </div>
          <div className='p-8'/>
          <div className='relative'>
          <FooterPlayer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
