const seoKeywords: string[] = [
  "music libraries",
  "music administrators",
  "music publishers",
  "sync licensing services",
  "music licensing",
  "royalty-free music",
  "production music",
  "music for film",
  "music for TV",
  "music for commercials",
  "background music",
  "stock music",
  "music catalog",
  "music rights",
  "music clearance",
  "music supervision",
  "sync deals",
  "music placement",
  "audio licensing",
  "music for video",
  "music rights management",
  "music rights clearance",
  "music copyright",
  "royalty-free music libraries",
  "music licensing agencies",
  "music composers",
  "music producers",
  "music artists",
  "music rights holders",
  "music publishers directory",
  "music licensing opportunities",
  "music for advertising",
  "instrumental music",
  "vocal music",
  "independent music licensing",
];

const seoKeywordsPhoenix: string[] = [
  "Phoenix music libraries",
  "Phoenix music administrators",
  "Phoenix music publishers",
  "Phoenix sync licensing services",
  "Phoenix music licensing",
  "Phoenix royalty-free music",
  "Phoenix production music",
  "Phoenix music for film",
  "Phoenix music for TV",
  "Phoenix music for commercials",
  "Phoenix background music",
  "Phoenix stock music",
  "Phoenix music catalog",
  "Phoenix music rights",
  "Phoenix music clearance",
  "Phoenix music supervision",
  "Phoenix sync deals",
  "Phoenix music placement",
  "Phoenix audio licensing",
  "Phoenix music for video",
  "Phoenix music rights management",
  "Phoenix music rights clearance",
  "Phoenix music copyright",
  "Phoenix royalty-free music libraries",
  "Phoenix music licensing agencies",
  "Phoenix music composers",
  "Phoenix music producers",
  "Phoenix music artists",
  "Phoenix music rights holders",
  "Phoenix music publishers directory",
  "Phoenix music licensing opportunities",
  "Phoenix music for advertising",
  "Phoenix instrumental music",
  "Phoenix vocal music",
  "Phoenix independent music licensing",
];

const allKeywords: string[] = [...seoKeywords, ...seoKeywordsPhoenix];
export default allKeywords;
